const std = @import("std");
const pi = std.math.pi;

pub fn nextGaussian(rand: std.Random, origin: f64, bound: f64) f64 {
    // Generate two uniform random numbers
    const r1 = rand.float(f64);
    const r2 = rand.float(f64);

    // Box-Muller transform
    const z0 = @sqrt(-2 * @log(r1)) * @cos(2 * pi * r2);

    return z0 * bound + origin;
}

const Station = struct {
    name: []const u8,
    mean_temperature: f64,

    pub fn next_measurement(self: Station, rand: std.Random) f64 {
        return nextGaussian(rand, self.mean_temperature, 10);
    }
};

pub fn main() !void {
    var args = std.process.args();
    _ = args.next();

    var n: usize = 1_000_000_000;
    if (args.next()) |first_arg| {
        n = try std.fmt.parseInt(usize, first_arg, 10);
    }

    const cwd = std.fs.cwd();

    var file = try cwd.createFile("measurements.txt", .{ .truncate = true });
    defer file.close();

    var buffer: [8192]u8 = undefined;
    var file_writer = file.writer(&buffer);
    const out = &file_writer.interface;

    const parent_progress_node = std.Progress.start(.{ .root_name = "Writting measurements.txt", .estimated_total_items = n });

    var prng = std.Random.DefaultPrng.init(blk: {
        var seed: u64 = undefined;
        try std.posix.getrandom(std.mem.asBytes(&seed));
        break :blk seed;
    });
    const rand = prng.random();

    for (0..n) |_| {
        parent_progress_node.completeOne();
        const station = Stations[rand.intRangeAtMost(u16, 0, Stations.len - 1)];
        try out.print("{s};{d:.1}\n", .{ station.name, station.next_measurement(rand) });
    }

    try out.flush();
}

const Stations = [_]Station{
    .{ .name = "Abha", .mean_temperature = 18.0 },
    .{ .name = "Abidjan", .mean_temperature = 26.0 },
    .{ .name = "Abéché", .mean_temperature = 29.4 },
    .{ .name = "Accra", .mean_temperature = 26.4 },
    .{ .name = "Addis Ababa", .mean_temperature = 16.0 },
    .{ .name = "Adelaide", .mean_temperature = 17.3 },
    .{ .name = "Aden", .mean_temperature = 29.1 },
    .{ .name = "Ahvaz", .mean_temperature = 25.4 },
    .{ .name = "Albuquerque", .mean_temperature = 14.0 },
    .{ .name = "Alexandra", .mean_temperature = 11.0 },
    .{ .name = "Alexandria", .mean_temperature = 20.0 },
    .{ .name = "Algiers", .mean_temperature = 18.2 },
    .{ .name = "Alice Springs", .mean_temperature = 21.0 },
    .{ .name = "Almaty", .mean_temperature = 10.0 },
    .{ .name = "Amsterdam", .mean_temperature = 10.2 },
    .{ .name = "Anadyr", .mean_temperature = -6.9 },
    .{ .name = "Anchorage", .mean_temperature = 2.8 },
    .{ .name = "Andorra la Vella", .mean_temperature = 9.8 },
    .{ .name = "Ankara", .mean_temperature = 12.0 },
    .{ .name = "Antananarivo", .mean_temperature = 17.9 },
    .{ .name = "Antsiranana", .mean_temperature = 25.2 },
    .{ .name = "Arkhangelsk", .mean_temperature = 1.3 },
    .{ .name = "Ashgabat", .mean_temperature = 17.1 },
    .{ .name = "Asmara", .mean_temperature = 15.6 },
    .{ .name = "Assab", .mean_temperature = 30.5 },
    .{ .name = "Astana", .mean_temperature = 3.5 },
    .{ .name = "Athens", .mean_temperature = 19.2 },
    .{ .name = "Atlanta", .mean_temperature = 17.0 },
    .{ .name = "Auckland", .mean_temperature = 15.2 },
    .{ .name = "Austin", .mean_temperature = 20.7 },
    .{ .name = "Baghdad", .mean_temperature = 22.77 },
    .{ .name = "Baguio", .mean_temperature = 19.5 },
    .{ .name = "Baku", .mean_temperature = 15.1 },
    .{ .name = "Baltimore", .mean_temperature = 13.1 },
    .{ .name = "Bamako", .mean_temperature = 27.8 },
    .{ .name = "Bangkok", .mean_temperature = 28.6 },
    .{ .name = "Bangui", .mean_temperature = 26.0 },
    .{ .name = "Banjul", .mean_temperature = 26.0 },
    .{ .name = "Barcelona", .mean_temperature = 18.2 },
    .{ .name = "Bata", .mean_temperature = 25.1 },
    .{ .name = "Batumi", .mean_temperature = 14.0 },
    .{ .name = "Beijing", .mean_temperature = 12.9 },
    .{ .name = "Beirut", .mean_temperature = 20.9 },
    .{ .name = "Belgrade", .mean_temperature = 12.5 },
    .{ .name = "Belize City", .mean_temperature = 26.7 },
    .{ .name = "Benghazi", .mean_temperature = 19.9 },
    .{ .name = "Bergen", .mean_temperature = 7.7 },
    .{ .name = "Berlin", .mean_temperature = 10.3 },
    .{ .name = "Bilbao", .mean_temperature = 14.7 },
    .{ .name = "Birao", .mean_temperature = 26.5 },
    .{ .name = "Bishkek", .mean_temperature = 11.3 },
    .{ .name = "Bissau", .mean_temperature = 27.0 },
    .{ .name = "Blantyre", .mean_temperature = 22.2 },
    .{ .name = "Bloemfontein", .mean_temperature = 15.6 },
    .{ .name = "Boise", .mean_temperature = 11.4 },
    .{ .name = "Bordeaux", .mean_temperature = 14.2 },
    .{ .name = "Bosaso", .mean_temperature = 30.0 },
    .{ .name = "Boston", .mean_temperature = 10.9 },
    .{ .name = "Bouaké", .mean_temperature = 26.0 },
    .{ .name = "Bratislava", .mean_temperature = 10.5 },
    .{ .name = "Brazzaville", .mean_temperature = 25.0 },
    .{ .name = "Bridgetown", .mean_temperature = 27.0 },
    .{ .name = "Brisbane", .mean_temperature = 21.4 },
    .{ .name = "Brussels", .mean_temperature = 10.5 },
    .{ .name = "Bucharest", .mean_temperature = 10.8 },
    .{ .name = "Budapest", .mean_temperature = 11.3 },
    .{ .name = "Bujumbura", .mean_temperature = 23.8 },
    .{ .name = "Bulawayo", .mean_temperature = 18.9 },
    .{ .name = "Burnie", .mean_temperature = 13.1 },
    .{ .name = "Busan", .mean_temperature = 15.0 },
    .{ .name = "Cabo San Lucas", .mean_temperature = 23.9 },
    .{ .name = "Cairns", .mean_temperature = 25.0 },
    .{ .name = "Cairo", .mean_temperature = 21.4 },
    .{ .name = "Calgary", .mean_temperature = 4.4 },
    .{ .name = "Canberra", .mean_temperature = 13.1 },
    .{ .name = "Cape Town", .mean_temperature = 16.2 },
    .{ .name = "Changsha", .mean_temperature = 17.4 },
    .{ .name = "Charlotte", .mean_temperature = 16.1 },
    .{ .name = "Chiang Mai", .mean_temperature = 25.8 },
    .{ .name = "Chicago", .mean_temperature = 9.8 },
    .{ .name = "Chihuahua", .mean_temperature = 18.6 },
    .{ .name = "Chișinău", .mean_temperature = 10.2 },
    .{ .name = "Chittagong", .mean_temperature = 25.9 },
    .{ .name = "Chongqing", .mean_temperature = 18.6 },
    .{ .name = "Christchurch", .mean_temperature = 12.2 },
    .{ .name = "City of San Marino", .mean_temperature = 11.8 },
    .{ .name = "Colombo", .mean_temperature = 27.4 },
    .{ .name = "Columbus", .mean_temperature = 11.7 },
    .{ .name = "Conakry", .mean_temperature = 26.4 },
    .{ .name = "Copenhagen", .mean_temperature = 9.1 },
    .{ .name = "Cotonou", .mean_temperature = 27.2 },
    .{ .name = "Cracow", .mean_temperature = 9.3 },
    .{ .name = "Da Lat", .mean_temperature = 17.9 },
    .{ .name = "Da Nang", .mean_temperature = 25.8 },
    .{ .name = "Dakar", .mean_temperature = 24.0 },
    .{ .name = "Dallas", .mean_temperature = 19.0 },
    .{ .name = "Damascus", .mean_temperature = 17.0 },
    .{ .name = "Dampier", .mean_temperature = 26.4 },
    .{ .name = "Dar es Salaam", .mean_temperature = 25.8 },
    .{ .name = "Darwin", .mean_temperature = 27.6 },
    .{ .name = "Denpasar", .mean_temperature = 23.7 },
    .{ .name = "Denver", .mean_temperature = 10.4 },
    .{ .name = "Detroit", .mean_temperature = 10.0 },
    .{ .name = "Dhaka", .mean_temperature = 25.9 },
    .{ .name = "Dikson", .mean_temperature = -11.1 },
    .{ .name = "Dili", .mean_temperature = 26.6 },
    .{ .name = "Djibouti", .mean_temperature = 29.9 },
    .{ .name = "Dodoma", .mean_temperature = 22.7 },
    .{ .name = "Dolisie", .mean_temperature = 24.0 },
    .{ .name = "Douala", .mean_temperature = 26.7 },
    .{ .name = "Dubai", .mean_temperature = 26.9 },
    .{ .name = "Dublin", .mean_temperature = 9.8 },
    .{ .name = "Dunedin", .mean_temperature = 11.1 },
    .{ .name = "Durban", .mean_temperature = 20.6 },
    .{ .name = "Dushanbe", .mean_temperature = 14.7 },
    .{ .name = "Edinburgh", .mean_temperature = 9.3 },
    .{ .name = "Edmonton", .mean_temperature = 4.2 },
    .{ .name = "El Paso", .mean_temperature = 18.1 },
    .{ .name = "Entebbe", .mean_temperature = 21.0 },
    .{ .name = "Erbil", .mean_temperature = 19.5 },
    .{ .name = "Erzurum", .mean_temperature = 5.1 },
    .{ .name = "Fairbanks", .mean_temperature = -2.3 },
    .{ .name = "Fianarantsoa", .mean_temperature = 17.9 },
    .{ .name = "Flores,  Petén", .mean_temperature = 26.4 },
    .{ .name = "Frankfurt", .mean_temperature = 10.6 },
    .{ .name = "Fresno", .mean_temperature = 17.9 },
    .{ .name = "Fukuoka", .mean_temperature = 17.0 },
    .{ .name = "Gabès", .mean_temperature = 19.5 },
    .{ .name = "Gaborone", .mean_temperature = 21.0 },
    .{ .name = "Gagnoa", .mean_temperature = 26.0 },
    .{ .name = "Gangtok", .mean_temperature = 15.2 },
    .{ .name = "Garissa", .mean_temperature = 29.3 },
    .{ .name = "Garoua", .mean_temperature = 28.3 },
    .{ .name = "George Town", .mean_temperature = 27.9 },
    .{ .name = "Ghanzi", .mean_temperature = 21.4 },
    .{ .name = "Gjoa Haven", .mean_temperature = -14.4 },
    .{ .name = "Guadalajara", .mean_temperature = 20.9 },
    .{ .name = "Guangzhou", .mean_temperature = 22.4 },
    .{ .name = "Guatemala City", .mean_temperature = 20.4 },
    .{ .name = "Halifax", .mean_temperature = 7.5 },
    .{ .name = "Hamburg", .mean_temperature = 9.7 },
    .{ .name = "Hamilton", .mean_temperature = 13.8 },
    .{ .name = "Hanga Roa", .mean_temperature = 20.5 },
    .{ .name = "Hanoi", .mean_temperature = 23.6 },
    .{ .name = "Harare", .mean_temperature = 18.4 },
    .{ .name = "Harbin", .mean_temperature = 5.0 },
    .{ .name = "Hargeisa", .mean_temperature = 21.7 },
    .{ .name = "Hat Yai", .mean_temperature = 27.0 },
    .{ .name = "Havana", .mean_temperature = 25.2 },
    .{ .name = "Helsinki", .mean_temperature = 5.9 },
    .{ .name = "Heraklion", .mean_temperature = 18.9 },
    .{ .name = "Hiroshima", .mean_temperature = 16.3 },
    .{ .name = "Ho Chi Minh City", .mean_temperature = 27.4 },
    .{ .name = "Hobart", .mean_temperature = 12.7 },
    .{ .name = "Hong Kong", .mean_temperature = 23.3 },
    .{ .name = "Honiara", .mean_temperature = 26.5 },
    .{ .name = "Honolulu", .mean_temperature = 25.4 },
    .{ .name = "Houston", .mean_temperature = 20.8 },
    .{ .name = "Ifrane", .mean_temperature = 11.4 },
    .{ .name = "Indianapolis", .mean_temperature = 11.8 },
    .{ .name = "Iqaluit", .mean_temperature = -9.3 },
    .{ .name = "Irkutsk", .mean_temperature = 1.0 },
    .{ .name = "Istanbul", .mean_temperature = 13.9 },
    .{ .name = "İzmir", .mean_temperature = 17.9 },
    .{ .name = "Jacksonville", .mean_temperature = 20.3 },
    .{ .name = "Jakarta", .mean_temperature = 26.7 },
    .{ .name = "Jayapura", .mean_temperature = 27.0 },
    .{ .name = "Jerusalem", .mean_temperature = 18.3 },
    .{ .name = "Johannesburg", .mean_temperature = 15.5 },
    .{ .name = "Jos", .mean_temperature = 22.8 },
    .{ .name = "Juba", .mean_temperature = 27.8 },
    .{ .name = "Kabul", .mean_temperature = 12.1 },
    .{ .name = "Kampala", .mean_temperature = 20.0 },
    .{ .name = "Kandi", .mean_temperature = 27.7 },
    .{ .name = "Kankan", .mean_temperature = 26.5 },
    .{ .name = "Kano", .mean_temperature = 26.4 },
    .{ .name = "Kansas City", .mean_temperature = 12.5 },
    .{ .name = "Karachi", .mean_temperature = 26.0 },
    .{ .name = "Karonga", .mean_temperature = 24.4 },
    .{ .name = "Kathmandu", .mean_temperature = 18.3 },
    .{ .name = "Khartoum", .mean_temperature = 29.9 },
    .{ .name = "Kingston", .mean_temperature = 27.4 },
    .{ .name = "Kinshasa", .mean_temperature = 25.3 },
    .{ .name = "Kolkata", .mean_temperature = 26.7 },
    .{ .name = "Kuala Lumpur", .mean_temperature = 27.3 },
    .{ .name = "Kumasi", .mean_temperature = 26.0 },
    .{ .name = "Kunming", .mean_temperature = 15.7 },
    .{ .name = "Kuopio", .mean_temperature = 3.4 },
    .{ .name = "Kuwait City", .mean_temperature = 25.7 },
    .{ .name = "Kyiv", .mean_temperature = 8.4 },
    .{ .name = "Kyoto", .mean_temperature = 15.8 },
    .{ .name = "La Ceiba", .mean_temperature = 26.2 },
    .{ .name = "La Paz", .mean_temperature = 23.7 },
    .{ .name = "Lagos", .mean_temperature = 26.8 },
    .{ .name = "Lahore", .mean_temperature = 24.3 },
    .{ .name = "Lake Havasu City", .mean_temperature = 23.7 },
    .{ .name = "Lake Tekapo", .mean_temperature = 8.7 },
    .{ .name = "Las Palmas de Gran Canaria", .mean_temperature = 21.2 },
    .{ .name = "Las Vegas", .mean_temperature = 20.3 },
    .{ .name = "Launceston", .mean_temperature = 13.1 },
    .{ .name = "Lhasa", .mean_temperature = 7.6 },
    .{ .name = "Libreville", .mean_temperature = 25.9 },
    .{ .name = "Lisbon", .mean_temperature = 17.5 },
    .{ .name = "Livingstone", .mean_temperature = 21.8 },
    .{ .name = "Ljubljana", .mean_temperature = 10.9 },
    .{ .name = "Lodwar", .mean_temperature = 29.3 },
    .{ .name = "Lomé", .mean_temperature = 26.9 },
    .{ .name = "London", .mean_temperature = 11.3 },
    .{ .name = "Los Angeles", .mean_temperature = 18.6 },
    .{ .name = "Louisville", .mean_temperature = 13.9 },
    .{ .name = "Luanda", .mean_temperature = 25.8 },
    .{ .name = "Lubumbashi", .mean_temperature = 20.8 },
    .{ .name = "Lusaka", .mean_temperature = 19.9 },
    .{ .name = "Luxembourg City", .mean_temperature = 9.3 },
    .{ .name = "Lviv", .mean_temperature = 7.8 },
    .{ .name = "Lyon", .mean_temperature = 12.5 },
    .{ .name = "Madrid", .mean_temperature = 15.0 },
    .{ .name = "Mahajanga", .mean_temperature = 26.3 },
    .{ .name = "Makassar", .mean_temperature = 26.7 },
    .{ .name = "Makurdi", .mean_temperature = 26.0 },
    .{ .name = "Malabo", .mean_temperature = 26.3 },
    .{ .name = "Malé", .mean_temperature = 28.0 },
    .{ .name = "Managua", .mean_temperature = 27.3 },
    .{ .name = "Manama", .mean_temperature = 26.5 },
    .{ .name = "Mandalay", .mean_temperature = 28.0 },
    .{ .name = "Mango", .mean_temperature = 28.1 },
    .{ .name = "Manila", .mean_temperature = 28.4 },
    .{ .name = "Maputo", .mean_temperature = 22.8 },
    .{ .name = "Marrakesh", .mean_temperature = 19.6 },
    .{ .name = "Marseille", .mean_temperature = 15.8 },
    .{ .name = "Maun", .mean_temperature = 22.4 },
    .{ .name = "Medan", .mean_temperature = 26.5 },
    .{ .name = "Mek'ele", .mean_temperature = 22.7 },
    .{ .name = "Melbourne", .mean_temperature = 15.1 },
    .{ .name = "Memphis", .mean_temperature = 17.2 },
    .{ .name = "Mexicali", .mean_temperature = 23.1 },
    .{ .name = "Mexico City", .mean_temperature = 17.5 },
    .{ .name = "Miami", .mean_temperature = 24.9 },
    .{ .name = "Milan", .mean_temperature = 13.0 },
    .{ .name = "Milwaukee", .mean_temperature = 8.9 },
    .{ .name = "Minneapolis", .mean_temperature = 7.8 },
    .{ .name = "Minsk", .mean_temperature = 6.7 },
    .{ .name = "Mogadishu", .mean_temperature = 27.1 },
    .{ .name = "Mombasa", .mean_temperature = 26.3 },
    .{ .name = "Monaco", .mean_temperature = 16.4 },
    .{ .name = "Moncton", .mean_temperature = 6.1 },
    .{ .name = "Monterrey", .mean_temperature = 22.3 },
    .{ .name = "Montreal", .mean_temperature = 6.8 },
    .{ .name = "Moscow", .mean_temperature = 5.8 },
    .{ .name = "Mumbai", .mean_temperature = 27.1 },
    .{ .name = "Murmansk", .mean_temperature = 0.6 },
    .{ .name = "Muscat", .mean_temperature = 28.0 },
    .{ .name = "Mzuzu", .mean_temperature = 17.7 },
    .{ .name = "N'Djamena", .mean_temperature = 28.3 },
    .{ .name = "Naha", .mean_temperature = 23.1 },
    .{ .name = "Nairobi", .mean_temperature = 17.8 },
    .{ .name = "Nakhon Ratchasima", .mean_temperature = 27.3 },
    .{ .name = "Napier", .mean_temperature = 14.6 },
    .{ .name = "Napoli", .mean_temperature = 15.9 },
    .{ .name = "Nashville", .mean_temperature = 15.4 },
    .{ .name = "Nassau", .mean_temperature = 24.6 },
    .{ .name = "Ndola", .mean_temperature = 20.3 },
    .{ .name = "New Delhi", .mean_temperature = 25.0 },
    .{ .name = "New Orleans", .mean_temperature = 20.7 },
    .{ .name = "New York City", .mean_temperature = 12.9 },
    .{ .name = "Ngaoundéré", .mean_temperature = 22.0 },
    .{ .name = "Niamey", .mean_temperature = 29.3 },
    .{ .name = "Nicosia", .mean_temperature = 19.7 },
    .{ .name = "Niigata", .mean_temperature = 13.9 },
    .{ .name = "Nouadhibou", .mean_temperature = 21.3 },
    .{ .name = "Nouakchott", .mean_temperature = 25.7 },
    .{ .name = "Novosibirsk", .mean_temperature = 1.7 },
    .{ .name = "Nuuk", .mean_temperature = -1.4 },
    .{ .name = "Odesa", .mean_temperature = 10.7 },
    .{ .name = "Odienné", .mean_temperature = 26.0 },
    .{ .name = "Oklahoma City", .mean_temperature = 15.9 },
    .{ .name = "Omaha", .mean_temperature = 10.6 },
    .{ .name = "Oranjestad", .mean_temperature = 28.1 },
    .{ .name = "Oslo", .mean_temperature = 5.7 },
    .{ .name = "Ottawa", .mean_temperature = 6.6 },
    .{ .name = "Ouagadougou", .mean_temperature = 28.3 },
    .{ .name = "Ouahigouya", .mean_temperature = 28.6 },
    .{ .name = "Ouarzazate", .mean_temperature = 18.9 },
    .{ .name = "Oulu", .mean_temperature = 2.7 },
    .{ .name = "Palembang", .mean_temperature = 27.3 },
    .{ .name = "Palermo", .mean_temperature = 18.5 },
    .{ .name = "Palm Springs", .mean_temperature = 24.5 },
    .{ .name = "Palmerston North", .mean_temperature = 13.2 },
    .{ .name = "Panama City", .mean_temperature = 28.0 },
    .{ .name = "Parakou", .mean_temperature = 26.8 },
    .{ .name = "Paris", .mean_temperature = 12.3 },
    .{ .name = "Perth", .mean_temperature = 18.7 },
    .{ .name = "Petropavlovsk-Kamchatsky", .mean_temperature = 1.9 },
    .{ .name = "Philadelphia", .mean_temperature = 13.2 },
    .{ .name = "Phnom Penh", .mean_temperature = 28.3 },
    .{ .name = "Phoenix", .mean_temperature = 23.9 },
    .{ .name = "Pittsburgh", .mean_temperature = 10.8 },
    .{ .name = "Podgorica", .mean_temperature = 15.3 },
    .{ .name = "Pointe-Noire", .mean_temperature = 26.1 },
    .{ .name = "Pontianak", .mean_temperature = 27.7 },
    .{ .name = "Port Moresby", .mean_temperature = 26.9 },
    .{ .name = "Port Sudan", .mean_temperature = 28.4 },
    .{ .name = "Port Vila", .mean_temperature = 24.3 },
    .{ .name = "Port-Gentil", .mean_temperature = 26.0 },
    .{ .name = "Portland (OR)", .mean_temperature = 12.4 },
    .{ .name = "Porto", .mean_temperature = 15.7 },
    .{ .name = "Prague", .mean_temperature = 8.4 },
    .{ .name = "Praia", .mean_temperature = 24.4 },
    .{ .name = "Pretoria", .mean_temperature = 18.2 },
    .{ .name = "Pyongyang", .mean_temperature = 10.8 },
    .{ .name = "Rabat", .mean_temperature = 17.2 },
    .{ .name = "Rangpur", .mean_temperature = 24.4 },
    .{ .name = "Reggane", .mean_temperature = 28.3 },
    .{ .name = "Reykjavík", .mean_temperature = 4.3 },
    .{ .name = "Riga", .mean_temperature = 6.2 },
    .{ .name = "Riyadh", .mean_temperature = 26.0 },
    .{ .name = "Rome", .mean_temperature = 15.2 },
    .{ .name = "Roseau", .mean_temperature = 26.2 },
    .{ .name = "Rostov-on-Don", .mean_temperature = 9.9 },
    .{ .name = "Sacramento", .mean_temperature = 16.3 },
    .{ .name = "Saint Petersburg", .mean_temperature = 5.8 },
    .{ .name = "Saint-Pierre", .mean_temperature = 5.7 },
    .{ .name = "Salt Lake City", .mean_temperature = 11.6 },
    .{ .name = "San Antonio", .mean_temperature = 20.8 },
    .{ .name = "San Diego", .mean_temperature = 17.8 },
    .{ .name = "San Francisco", .mean_temperature = 14.6 },
    .{ .name = "San Jose", .mean_temperature = 16.4 },
    .{ .name = "San José", .mean_temperature = 22.6 },
    .{ .name = "San Juan", .mean_temperature = 27.2 },
    .{ .name = "San Salvador", .mean_temperature = 23.1 },
    .{ .name = "Sana'a", .mean_temperature = 20.0 },
    .{ .name = "Santo Domingo", .mean_temperature = 25.9 },
    .{ .name = "Sapporo", .mean_temperature = 8.9 },
    .{ .name = "Sarajevo", .mean_temperature = 10.1 },
    .{ .name = "Saskatoon", .mean_temperature = 3.3 },
    .{ .name = "Seattle", .mean_temperature = 11.3 },
    .{ .name = "Ségou", .mean_temperature = 28.0 },
    .{ .name = "Seoul", .mean_temperature = 12.5 },
    .{ .name = "Seville", .mean_temperature = 19.2 },
    .{ .name = "Shanghai", .mean_temperature = 16.7 },
    .{ .name = "Singapore", .mean_temperature = 27.0 },
    .{ .name = "Skopje", .mean_temperature = 12.4 },
    .{ .name = "Sochi", .mean_temperature = 14.2 },
    .{ .name = "Sofia", .mean_temperature = 10.6 },
    .{ .name = "Sokoto", .mean_temperature = 28.0 },
    .{ .name = "Split", .mean_temperature = 16.1 },
    .{ .name = "St. John's", .mean_temperature = 5.0 },
    .{ .name = "St. Louis", .mean_temperature = 13.9 },
    .{ .name = "Stockholm", .mean_temperature = 6.6 },
    .{ .name = "Surabaya", .mean_temperature = 27.1 },
    .{ .name = "Suva", .mean_temperature = 25.6 },
    .{ .name = "Suwałki", .mean_temperature = 7.2 },
    .{ .name = "Sydney", .mean_temperature = 17.7 },
    .{ .name = "Tabora", .mean_temperature = 23.0 },
    .{ .name = "Tabriz", .mean_temperature = 12.6 },
    .{ .name = "Taipei", .mean_temperature = 23.0 },
    .{ .name = "Tallinn", .mean_temperature = 6.4 },
    .{ .name = "Tamale", .mean_temperature = 27.9 },
    .{ .name = "Tamanrasset", .mean_temperature = 21.7 },
    .{ .name = "Tampa", .mean_temperature = 22.9 },
    .{ .name = "Tashkent", .mean_temperature = 14.8 },
    .{ .name = "Tauranga", .mean_temperature = 14.8 },
    .{ .name = "Tbilisi", .mean_temperature = 12.9 },
    .{ .name = "Tegucigalpa", .mean_temperature = 21.7 },
    .{ .name = "Tehran", .mean_temperature = 17.0 },
    .{ .name = "Tel Aviv", .mean_temperature = 20.0 },
    .{ .name = "Thessaloniki", .mean_temperature = 16.0 },
    .{ .name = "Thiès", .mean_temperature = 24.0 },
    .{ .name = "Tijuana", .mean_temperature = 17.8 },
    .{ .name = "Timbuktu", .mean_temperature = 28.0 },
    .{ .name = "Tirana", .mean_temperature = 15.2 },
    .{ .name = "Toamasina", .mean_temperature = 23.4 },
    .{ .name = "Tokyo", .mean_temperature = 15.4 },
    .{ .name = "Toliara", .mean_temperature = 24.1 },
    .{ .name = "Toluca", .mean_temperature = 12.4 },
    .{ .name = "Toronto", .mean_temperature = 9.4 },
    .{ .name = "Tripoli", .mean_temperature = 20.0 },
    .{ .name = "Tromsø", .mean_temperature = 2.9 },
    .{ .name = "Tucson", .mean_temperature = 20.9 },
    .{ .name = "Tunis", .mean_temperature = 18.4 },
    .{ .name = "Ulaanbaatar", .mean_temperature = -0.4 },
    .{ .name = "Upington", .mean_temperature = 20.4 },
    .{ .name = "Ürümqi", .mean_temperature = 7.4 },
    .{ .name = "Vaduz", .mean_temperature = 10.1 },
    .{ .name = "Valencia", .mean_temperature = 18.3 },
    .{ .name = "Valletta", .mean_temperature = 18.8 },
    .{ .name = "Vancouver", .mean_temperature = 10.4 },
    .{ .name = "Veracruz", .mean_temperature = 25.4 },
    .{ .name = "Vienna", .mean_temperature = 10.4 },
    .{ .name = "Vientiane", .mean_temperature = 25.9 },
    .{ .name = "Villahermosa", .mean_temperature = 27.1 },
    .{ .name = "Vilnius", .mean_temperature = 6.0 },
    .{ .name = "Virginia Beach", .mean_temperature = 15.8 },
    .{ .name = "Vladivostok", .mean_temperature = 4.9 },
    .{ .name = "Warsaw", .mean_temperature = 8.5 },
    .{ .name = "Washington, D.C.", .mean_temperature = 14.6 },
    .{ .name = "Wau", .mean_temperature = 27.8 },
    .{ .name = "Wellington", .mean_temperature = 12.9 },
    .{ .name = "Whitehorse", .mean_temperature = -0.1 },
    .{ .name = "Wichita", .mean_temperature = 13.9 },
    .{ .name = "Willemstad", .mean_temperature = 28.0 },
    .{ .name = "Winnipeg", .mean_temperature = 3.0 },
    .{ .name = "Wrocław", .mean_temperature = 9.6 },
    .{ .name = "Xi'an", .mean_temperature = 14.1 },
    .{ .name = "Yakutsk", .mean_temperature = -8.8 },
    .{ .name = "Yangon", .mean_temperature = 27.5 },
    .{ .name = "Yaoundé", .mean_temperature = 23.8 },
    .{ .name = "Yellowknife", .mean_temperature = -4.3 },
    .{ .name = "Yerevan", .mean_temperature = 12.4 },
    .{ .name = "Yinchuan", .mean_temperature = 9.0 },
    .{ .name = "Zagreb", .mean_temperature = 10.7 },
    .{ .name = "Zanzibar City", .mean_temperature = 26.0 },
    .{ .name = "Zürich", .mean_temperature = 9.3 },
};
